# Generated by Django 5.0.2 on 2024-03-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['status']},
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
