# Generated by Django 5.0.2 on 2024-03-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_jobs_options_alter_jobs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='worth',
            field=models.CharField(default='$00.00', max_length=50),
        ),
    ]
