# Generated by Django 5.0.2 on 2024-03-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_jobs_worth'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='cartegory',
            field=models.CharField(default='coding', max_length=50),
        ),
    ]
